# Generated by Django 4.0.5 on 2022-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='DetalleProducto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
